# Site settings
title: Kingdom
description: A smarter card picker for the Dominion card game.
repository: YtnomSnrub/kingdom
github_username: YtnomSnrub

github: [metadata]

# Build settings
markdown: kramdown
source: ./app
